name: Trigger auto deployment for ca2404240060002419

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca2404240060002419-AutoDeployTrigger-d9d8c7a4-e73f-470e-83ca-f73dc4dcb829.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CA2404240060002419_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CA2404240060002419_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CA2404240060002419_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CA2404240060002419_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CA2404240060002419_REGISTRY_PASSWORD }}
          containerAppName: ca2404240060002419
          resourceGroup: rg2404240060002419
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


